---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)

data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group) %>% 
  select(borough, neighbourhood, stars, price, room_type, lat, long) %>% 
  drop_na(stars)
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# now adding input widgets so user can interact 
boroughs = nyc_airbnb %>%  distinct(borough) %>%  pull()

selectInput(
  inputId = "borough_choice",
  label = "Borough Choice",
  choices = boroughs
)

sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min = 50, max = 1000, value = c(100, 250)
)

room_types = nyc_airbnb %>%  distinct(room_type) %>%  pull()
radioButtons(
  inputId = "room_choice",
  label = h3("Room Type"),
  choices = room_types
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>%
  filter(
    borough == input[["borough_choice"]], 
    price >= input[["price_range"]][1],
    price <= input[["price_range"]][2],
    room_type == input[["room_choice"]]) %>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price)})









renderPrint({ 
  input[["borough_choice"]]
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>% 
    filter(
      borough == input[["borough_choice"]],
      room_type == input[["room_choice"]]
    ) %>% 
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})


renderPrint({ 
  input[["price_range"]]
})
```

### Chart C

```{r}

```

